#ifndef ENUMGAME_H
#define ENUMGAME_H

enum
{

	GAMEMODE, TITLEMODE, CLICKTOSTART, FOCUSMODE, MAPMODE, TELEPORTERMODE, GAMECOMPLETE,  GAMECOMPLETE2, EDITORMODE, PRELOADER

};

enum input_type : int {
    swipeinput, holdinput
};

#endif /* ENUMGAME_H */
